When registering a hookimpl which is declared as ``hookwrapper=True`` but whose
function is not a generator function, a ``PluggyValidationError`` exception is
now raised.

Previously this problem would cause an error only later, when calling the hook.

In the unlikely case that you have a hookwrapper that *returns* a generator
instead of yielding directly, for example:

.. code-block:: python

    def my_hook_real_implementation(arg):
        print("before")
        yield
        print("after")


    @hookimpl(hookwrapper=True)
    def my_hook(arg):
        return my_hook_implementation(arg)

change it to use ``yield from`` instead:

.. code-block:: python

    @hookimpl(hookwrapper=True)
    def my_hook(arg):
        yield from my_hook_implementation(arg)
